# lincoln imports

In [1]:
import numpy as np 
%load_ext autoreload
%autoreload 2 

In [10]:
import lincoln
from lincoln.layers import Dense
from lincoln.losses import SoftmaxCrossEntropy, MeanSquaredError
from lincoln.optimizers import Optimizer, SGD, SGDMomentum
from lincoln.activations import Sigmoid, Tanh, Linear, ReLU
from lincoln.network import NeuralNetwork
from lincoln.train import Trainer
from lincoln.utils import mnist
from lincoln.utils.np_utils import softmax

In [11]:
X_train, y_train, X_test, y_test = mnist.load()

Download complete.
Save complete.


In [13]:
num_labels_train = len(y_train)
num_labels_train

60000

In [15]:
num_labels_test = len(y_test)
num_labels_test

10000

In [57]:
# one-hot encode
num_labels = len(y_train)
train_labels = np.zeros((num_labels, 10))
for i in range(num_labels):
    train_labels[i][y_train[i]] = 1

num_labels_test = len(y_test)
test_labels = np.zeros((num_labels_test, 10))
for i in range(num_labels_test):
    test_labels[i][y_test[i]] = 1

In [59]:
for i in range(num_labels):
    print(train_labels[i], '->>>>>', y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 1. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[1. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 1. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[1. 0. 0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 1. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 1. 

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 1. 0. 0. 0. 

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[1. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 0. 0. 1. 

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.] ->>>>> 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] ->>>>> 9
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] ->>>>> 8
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] ->>>>> 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] ->>>>> 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] ->>>>> 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] ->>>>> 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.] ->>>>> 

KeyboardInterrupt: 

## MNIST DEMOS 

### Scale data to mean 0, variance 1 

In [60]:
X_train, X_test = X_train - np.mean(X_train), X_test - np.mean(X_train)

In [61]:
np.min(X_train), np.max(X_train), np.min(X_test), np.max(X_test)

(-33.318421449829934,
 221.68157855017006,
 -33.318421449829934,
 221.68157855017006)

In [62]:
X_train, X_test = X_train / np.std(X_train), X_test / np.std(X_train)

In [63]:
np.min(X_train), np.max(X_train), np.min(X_test), np.max(X_test)

(-0.424073894391566, 2.821543345689335, -0.424073894391566, 2.821543345689335)

In [64]:
def calc_accuracy_model(model, test_set):
    return print(f'''The model validation accuracy is: 
        {np.equal(np.argmax(model.forward(test_set, inference=True), axis=1), y_test).sum() 
            * 100.0 / test_set.shape[0]:.2f}%''')
    

#### Softmax cross entropy

### Trying sigmoid activation 

In [68]:
model = NeuralNetwork(
                        layers=[Dense(neurons=89, 
                                      activation=Tanh()),
                                Dense(neurons=10, 
                                      activation=Sigmoid())],
                                loss = MeanSquaredError(normalize=False), 
                                seed=20190119)

trainer = Trainer(model, SGD(0.1))
trainer.fit(X_train, train_labels, X_test, test_labels,
            epochs = 50,
            eval_every = 10,
            seed=20190119,
            batch_size=60);
print()
calc_accuracy_model(model, X_test)

Validation loss after 10 epochs is 0.611
Validation loss after 20 epochs is 0.429
Validation loss after 30 epochs is 0.387
Validation loss after 40 epochs is 0.373
Validation loss after 50 epochs is 0.365

The model validation accuracy is: 
        72.68%


Note: even if we normalize the outputs of a classification model with mean squared error loss, it still doesn't help:

In [69]:
model = NeuralNetwork(
    layers=[Dense(neurons=89, 
                  activation=Tanh()),
            Dense(neurons=10, 
                  activation=Sigmoid())],
            loss = MeanSquaredError(normalize=True), 
seed=20190119)

trainer = Trainer(model, SGD(0.1))
trainer.fit(X_train, train_labels, X_test, test_labels,
            epochs = 50,
            eval_every = 10,
            seed=20190119,
            batch_size=60);

calc_accuracy_model(model, X_test)

Validation loss after 10 epochs is 0.952

Loss increased after epoch 20, final loss was 0.952, 
using the model from epoch 10
The model validation accuracy is: 
        41.73%
